# Generated by Django 4.2.7 on 2025-06-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step1', models.TextField(blank=True, help_text='Company name', null=True)),
                ('step2', models.CharField(blank=True, help_text='Service type', max_length=100, null=True)),
                ('step3', models.CharField(blank=True, help_text='When issue occurred', max_length=100, null=True)),
                ('step4', models.CharField(blank=True, help_text='Company acknowledgment', max_length=100, null=True)),
                ('step5', models.CharField(blank=True, help_text='Primary goal', max_length=100, null=True)),
                ('step6', models.CharField(blank=True, help_text='How heard about us', max_length=100, null=True)),
                ('step7', models.CharField(blank=True, help_text='Preferred communication', max_length=100, null=True)),
                ('step8', models.TextField(blank=True, help_text='Case summary', null=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(default='US', max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
