# Generated by Django 4.2.7 on 2025-06-29 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('step1', django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Company name', null=True))),
                ('step2', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Service type', max_length=100, null=True))),
                ('step3', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='When issue occurred', max_length=100, null=True))),
                ('step4', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Company acknowledgment', max_length=100, null=True))),
                ('step5', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Primary goal', max_length=100, null=True))),
                ('step6', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='How heard about us', max_length=100, null=True))),
                ('step7', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Preferred communication', max_length=100, null=True))),
                ('step8', django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Case summary', null=True))),
                ('name', django_cryptography.fields.encrypt(models.CharField(max_length=200))),
                ('email', django_cryptography.fields.encrypt(models.EmailField(max_length=254))),
                ('phone', django_cryptography.fields.encrypt(models.CharField(max_length=20))),
                ('country', models.CharField(default='US', max_length=10)),
                ('email_hash', models.CharField(db_index=True, default='', max_length=64)),
                ('phone_hash', models.CharField(db_index=True, default='', max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address_hash', models.CharField(db_index=True, default='', max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('data_classification', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted')], default='CONFIDENTIAL', max_length=20)),
                ('retention_date', models.DateTimeField(blank=True, null=True)),
                ('anonymized', models.BooleanField(default=False)),
                ('checksum', models.CharField(default='', editable=False, max_length=64)),
            ],
            options={
                'verbose_name': 'Encrypted Form Submission',
                'verbose_name_plural': 'Encrypted Form Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['submitted_at', 'country'], name='submissions_submitt_4c63da_idx'), models.Index(fields=['email_hash'], name='submissions_email_h_ea23a7_idx'), models.Index(fields=['anonymized', 'retention_date'], name='submissions_anonymi_d7f940_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('description', models.TextField()),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('affected_submissions', models.ManyToManyField(blank=True, to='submissions.submission')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRetentionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ANONYMIZE', 'Anonymize'), ('DELETE', 'Delete'), ('EXPORT', 'Export'), ('RESTORE', 'Restore')], max_length=20)),
                ('submission_uuid', models.UUIDField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
